name: Node.js CI
on:
  push:
    branches: [gh-pages]
  pull_request:
    branches: [gh-pages]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm

      - name: Build
        run: |
          yarn install --frozen-lockfile
          yarn run build
          yarn run export
          touch out/.nojekyll
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: develop
          folder: out
